const { parsed: localEnv } = require("dotenv").config();

module.exports = {
  publicRuntimeConfig: {
    NEXT_PUBLIC_CONTACT_EMAIL: localEnv && localEnv.NEXT_PUBLIC_CONTACT_EMAIL,
    NEXT_PUBLIC_SITE_NAME: localEnv && localEnv.NEXT_PUBLIC_SITE_NAME,
    NEXT_PUBLIC_DEFAULT_DOMAIN: localEnv && localEnv.NEXT_PUBLIC_DEFAULT_DOMAIN,
    NEXT_PUBLIC_RECAPTCHA_SITE_KEY: localEnv && localEnv.NEXT_PUBLIC_RECAPTCHA_SITE_KEY,
    NEXT_PUBLIC_REPORT_EMAIL: localEnv && localEnv.NEXT_PUBLIC_REPORT_EMAIL,
    NEXT_PUBLIC_DISALLOW_ANONYMOUS_LINKS: localEnv && localEnv.NEXT_PUBLIC_DISALLOW_ANONYMOUS_LINKS,
    NEXT_PUBLIC_DISALLOW_REGISTRATION: localEnv && localEnv.NEXT_PUBLIC_DISALLOW_REGISTRATION
  }
};
